name: Build and Deploy Site

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Checkout deployment branch
        uses: actions/checkout@v2
        with:
          ref: test-deployment
          path: _site

      - name: Setup Node.js 16 LTS (Gallium)
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/gallium'

      - name: Install dependencies
        run: npm ci

      - name: Build site assets
        run: npm run build

      - name: Update deployment branch
        run: ./scripts/update-gh-pages.sh
        env:
          DEPLOYMENT_FOLDER: _site
          GITHUB_TOKEN: ${{ secrets.github_token }}
