name: Build and Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20 LTS (Iron)
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/iron'

      - name: Install dependencies
        run: npm ci

      - name: Build site assets
        run: npm run build

      - name: Update deployment branch
        run: ./scripts/update-gh-pages.sh
        env:
          DEPLOYMENT_BRANCH: deployment
          DEPLOYMENT_FOLDER: _site
          GITHUB_TOKEN: ${{ secrets.github_token }}
