name: Test Build

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node.js 16 LTS (Gallium)
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/hydrogen'

      - name: Install dependencies
        run: npm ci

      - name: Build site assets
        run: npm run build

      - name: Upload generated site
        uses: actions/upload-artifact@v3
        with:
          name: generated-site
          path: _site
