name: Test Build

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 20 LTS (Iron)
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/iron'

      - name: Install dependencies
        run: npm ci

      - name: Build site assets
        run: npm run build

      - name: Upload generated site
        uses: actions/upload-artifact@v4
        with:
          name: generated-site
          path: _site
